#!/bin/sh /etc/rc.common
# padavan-services - Padavan 重写版服务层 procd 骨架
#
# M3 原型：一个聚合 init 脚本管理注册表中的全部服务，
# 正式版按 padavan_service.procd_instance 拆分为独立
# /etc/init.d/padavan-<svc> 脚本，本文件保留作 procd 接入示范。
#
# 用法:
#   /etc/init.d/padavan-services start|stop|restart [svc]
#   不带 svc 时作用于注册表全部服务（顺序按依赖编排）

START=95
STOP=10
USE_PROCD=1

RC_NG=/usr/sbin/rc-ng
SERVICES="wan firewall dnsmasq upnp pptp"

start_service() {
    local svc
    if [ -n "$1" ]; then
        $RC_NG start "$1"
    else
        for svc in $SERVICES; do
            $RC_NG start "$svc"
        done
    fi
}

stop_service() {
    local svc
    if [ -n "$1" ]; then
        $RC_NG stop "$1"
    else
        for svc in $SERVICES; do
            $RC_NG stop "$svc"
        done
    fi
}

reload_service() {
    [ -n "$1" ] && $RC_NG reload "$1"
}

restart() {
    local svc
    if [ -n "$1" ]; then
        $RC_NG restart "$1"
    else
        for svc in $SERVICES; do
            $RC_NG restart "$svc"
        done
    fi
}

# 正式版示例：独立 procd 实例声明
# start_service() {
#     procd_open_instance padavan-dnsmasq
#     procd_set_param command /usr/sbin/dnsmasq --conf-file=/etc/dnsmasq.conf
#     procd_set_param respawn
#     procd_close_instance
# }
